advans/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('cve/', include('cve.urls')),
    path('admin/', admin.site.urls),
]

cve/urls.py
from django.urls import path

from . import views

app_name = 'cve'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:pk>/', views.DetailView.as_view(), name='detail'),
    path('archives/', views.ArchivesView.as_view(), name='archives'),
]

cve/models.py
import datetime

from django.db import models
from django.utils import timezone
from djongo import models


class CVE(models.Model):

    cve_name = models.CharField(max_length=20)
    summary = models.TextField(default="...")
    pub_date = models.DateTimeField('date published')
    cvss = models.TextField(default="...")
    # cve_criticity = models.CharField(max_length=1, choices=CRITICITY_CODE)
    cve_status = models.TextField(default="...")
    _id = models.TextField(default="...") #https://stackoverflow.com/questions/66085516/pymongo-errors-duplicatekeyerror-e11000-duplicate-key-error-collection
    
    def __str__(self):
        return self.cve_name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

cve/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import CVE


class IndexView(generic.ListView):
    template_name = 'cve/index.html'
    context_object_name = 'latest_cve_list'

    def get_queryset(self):
        return CVE.objects.order_by('-pub_date')


class ArchivesView(generic.ListView):
    template_name = 'cve/archives.html'
    context_object_name = 'latest_cve_list'

    def get_queryset(self):
        return CVE.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = CVE
    template_name = 'cve/detail.html'

cve/templates/cve/archives.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cve/style.css' %}" />

<div class="main-container">
    <div class="sidebar-left">
        <div class="logo-title">
        <img
            src="../../static/cve/images/advans_survey.png"
            alt="Logo Advans Survey"
        />
        <h2>Advans CVE Survey</h2>
        </div>
        <div class="links-sidebar-container">
            <a href="{% url 'cve:index' %}" class="link-sidebar">CVE actuelles</a>
        </div>
        <div class="settings-sidebar-container">
            <a href="{% url 'admin:index' %}">
                <img
                src="../../static/cve/images/settings.png"
                alt="Settings Icon"
                />
            </a>
      </div>
    </div>

    <div class="container-right">
      <div class="cve-main-container">
        <div class="cve-sub-container">
        <div class="cve-container-upbar">
          <span class="cve-upbar-option">Filtres : ...</span>
          <span class="cve-upbar-option">Supprimer : ...</span>
          <span class="cve-upbar-option">Archiver : ...</span><span class="cve-upbar-option">Confirmer</span>
        </div>
          <div class="cve-container">
          {% if latest_cve_list %}
          <table class="cve-table">
            <thead>
                <tr>
                    <th colspan="1"></th>
                    <th colspan="1">Id</th>
                    <th colspan="1">Nom</th>
                    <th colspan="1">Date</th>
                    <th colspan="1" class="summary">Sommaire</th>
                    <th colspan="1">Criticité</th>
                    <th colspan="1">Archiver</th>
                    <th colspan="1">Supprimer</th>
                </tr>
            </thead>
            <tbody>
            {% for cve in latest_cve_list %}
                <tr>
                    <td><input type="checkbox"></td>
                    <td>{{ cve.Id }}</td>
                    <td><a href="{% url 'cve:detail' cve.cve_name %}"
                      >{{ cve.cve_name }}</a
                    ></td>
                    <td>{{ cve.pub_date }}</td>
                    <td>{{ cve.cve_summary|truncatewords:20 }}</td>
                    <td>
                      <div class="criticity criticity-{{ cve.cvss }}">
                        {{ cve.cvss }}
                      </div>
                    </td>
                    <td><div class="archive-button"><a href="#">Archiver</a></div></td>
                    <td><div class="delete-button"><a href="#">Supprimer</a></div></td>
                  </tr>
            {% endfor %}
              </tbody>
          </table>
          {% else %}
            <p>No polls are available.</p>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

cve/templates/cve/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cve/style.css' %}" />

<div class="main-container">
  <div class="sidebar-left">
    <div class="logo-title">
      <img
        src="../../static/cve/images/advans_survey.png"
        alt="Logo Advans Survey"
      />
      <h2>Advans CVE Survey</h2>
    </div>
    <div class="links-sidebar-container">
      <a href="{% url 'cve:index' %}" class="link-sidebar">CVE actuelles</a>
      <a href="{% url 'cve:archives' %}" class="link-sidebar">CVE archivées</a>
    </div>
    <div class="settings-sidebar-container">
      <a href="{% url 'admin:index' %}">
        <img src="../../static/cve/images/settings.png" alt="Settings Icon" />
      </a>
    </div>
  </div>

  <div class="container-right">
    <div class="cve-main-container">
      <div class="cve-sub-container">
        <div class="cve-container-detail">
            <div
              style="
                padding: 10px;
                margin-top: 25px;
                margin-bottom: 25px;
                width: 90%;
                box-shadow: -2px 0px 15px 1px #d2d2d2;
                border-radius: 5px;
              "
            >
              <p><span class="span-detail">Id :</span> {{ cve.cve_name }}</p>
              <p><span class="span-detail">Nom :</span> {{ cve.cve_name }}</p>
              <p><span class="span-detail">Date :</span> {{ cve.pub_date }}</p>
              <p><span class="span-detail">Description :</span> {{ cve.summary }}</p>
              <p><span class="span-detail">Criticité :</span></p>
                <div class="detail-element criticity criticity-{{ cve.cvss }}">
                  {{ cve.cvss }}
                </div>
              <p><span class="span-detail">Statut :</span></p>
                <div class="detail-element status status-{{ cve.cve_status }}">
                  {{cve.cve_status}}
                </div>
                <hr style="color:green;">
              <p><span class="span-detail">Actions :</span></p>
              <div class="detail-element archive-button"><a href="#">Archiver</a></div>
              <div class="detail-element delete-button"><a href="#">Supprimer</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

cve/templates/cve/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cve/style.css' %}" />

<div class="main-container">
    <div class="sidebar-left">
        <div class="logo-title">
        <img
            src="../../static/cve/images/advans_survey.png"
            alt="Logo Advans Survey"
        />
        <h2>Advans CVE Survey</h2>
        </div>
        <div class="links-sidebar-container">
            <a href="{% url 'cve:archives' %}" class="link-sidebar">CVE archivées</a>
        </div>
        <div class="settings-sidebar-container">
          <a href="{% url 'admin:index' %}">
            <img
              src="../../static/cve/images/settings.png"
              alt="Settings Icon"
            />
          </a>
      </div>
    </div>

    <div class="container-right">
      <div class="cve-main-container">
        <div class="cve-sub-container">
        <div class="cve-container-upbar">
          <span class="cve-upbar-option">Filtres : ...</span>
          <span class="cve-upbar-option">Supprimer : ...</span>
          <span class="cve-upbar-option">Archiver : ...</span><span class="cve-upbar-option">Confirmer</span>
        </div>
          <div class="cve-container">
          <table class="cve-table">
            <thead>
                <tr>
                    <th colspan="1"></th>
                    <th colspan="1">Id</th>
                    <th colspan="1">Nom</th>
                    <th colspan="1">Date</th>
                    <th colspan="1" class="summary">Description</th>
                    <th colspan="1">Criticité</th>
                    <th colspan="1">Archiver</th>
                    <th colspan="1">Supprimer</th>
                </tr>
            </thead>
            <tbody>
            {% for cve in latest_cve_list %}
                <tr>
                    <td><input type="checkbox"></td>
                    <td>{{ cve.Id }}</td>
                    <td><a href="{% url 'cve:detail' cve.id %}"
                      >{{ cve.cve_name }}</a
                    ></td>
                    <td>{{ cve.pub_date }}</td>
                    <td>{{ cve.summary|truncatewords:20 }}</td>
                    <td>
                      <div class="criticity criticity-{{ cve.cvss }}">
                        {{ cve.cvss }}
                      </div>
                    </td>
                    <td><div class="archive-button"><a href="#">Archiver</a></div></td>
                    <td><div class="delete-button"><a href="#">Supprimer</a></div></td>
                  </tr>
            {% endfor %}
              </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>